"use client"
import Head from 'next/head'
import { Canvas, useFrame  } from '@react-three/fiber'
import {useRef, useState} from "react";

export default function Home() {
  return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link href="../styles/output.css" rel="stylesheet"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main Style={"width:1900px; height:738px"}  class="bg-white">
          <div Style={"width:80%; height:100%; margin: 10%,0"} >

            <Canvas>
              <RenderPickels/>

              <ambientLight intensity={0.05} />
              <directionalLight color="#fff9db" position={[0, 1, 1]} />
            </Canvas>
            <div className={"overlap"}>
              hey texttttttttttttttttttttttttttttttttttt
              overlap test
            </div>
          </div>
        </main>
      </>
  )
}

function RenderPickels(){
  const ref = useRef()
  useFrame((state, delta) => (ref.current.rotation.y += delta * 0.2))
  const [hovered, hover] = useState(false)
  const [scale, setScale] = useState(1)

  return (
      <mesh
          ref={ref}
          position={[-1,0,0]}
          scale={scale}
          onPointerOver={(event) => (setScale(scale+0.2) , hover(true))}
          onPointerOut={(event) => hover(false)}>

        <boxGeometry args={[1, 1, 1]} />
        <meshStandardMaterial color={hovered ? 'hotpink' : 'orange'}/>
      </mesh>
  )
}
